[tool.poetry]
name = "supportbank"
version = "0.1.0"
description = ""
authors = ["Anca Radu <anca.radu@softwire.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
